config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'welcome#index'

  devise_for :users
  resources :users

  resources :submission_questions

  resources :submissions

  resources :question_attachments

  resources :file_uploads

  resources :questions

end

app/models/question_attachment.rb
class QuestionAttachment < ActiveRecord::Base
end

app/controllers/question_attachments_controller.rb
class QuestionAttachmentsController < ApplicationController
  before_action :set_question_attachment, only: [:show, :edit, :update, :destroy]

  # GET /question_attachments
  # GET /question_attachments.json
  def index
    @question_attachments = QuestionAttachment.all
  end

  # GET /question_attachments/1
  # GET /question_attachments/1.json
  def show
  end

  # GET /question_attachments/new
  def new
    @question_attachment = QuestionAttachment.new
  end

  # GET /question_attachments/1/edit
  def edit
  end

  # POST /question_attachments
  # POST /question_attachments.json
  def create
    @question_attachment = QuestionAttachment.new(question_attachment_params)

    respond_to do |format|
      if @question_attachment.save
        format.html { redirect_to @question_attachment, notice: 'Question attachment was successfully created.' }
        format.json { render :show, status: :created, location: @question_attachment }
      else
        format.html { render :new }
        format.json { render json: @question_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_attachments/1
  # PATCH/PUT /question_attachments/1.json
  def update
    respond_to do |format|
      if @question_attachment.update(question_attachment_params)
        format.html { redirect_to @question_attachment, notice: 'Question attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_attachment }
      else
        format.html { render :edit }
        format.json { render json: @question_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_attachments/1
  # DELETE /question_attachments/1.json
  def destroy
    @question_attachment.destroy
    respond_to do |format|
      format.html { redirect_to question_attachments_url, notice: 'Question attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_attachment
      @question_attachment = QuestionAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_attachment_params
      params.require(:question_attachment).permit(:question_id, :file_upload_id, :display_order)
    end
end

app/helpers/question_attachments_helper.rb
module QuestionAttachmentsHelper
end

app/views/question_attachments/_form.html.erb
<%= form_for(@question_attachment) do |f| %>
  <% if @question_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_attachment.errors.count, "error") %> prohibited this question_attachment from being saved:</h2>

      <ul>
      <% @question_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :file_upload_id %><br>
    <%= f.number_field :file_upload_id %>
  </div>
  <div class="field">
    <%= f.label :display_order %><br>
    <%= f.number_field :display_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_attachments/edit.html.erb
<h1>Editing question_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_attachment %> |
<%= link_to 'Back', question_attachments_path %>

app/views/question_attachments/index.html.erb
<h1>Listing question_attachments</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>File upload</th>
      <th>Display order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_attachments.each do |question_attachment| %>
      <tr>
        <td><%= question_attachment.question_id %></td>
        <td><%= question_attachment.file_upload_id %></td>
        <td><%= question_attachment.display_order %></td>
        <td><%= link_to 'Show', question_attachment %></td>
        <td><%= link_to 'Edit', edit_question_attachment_path(question_attachment) %></td>
        <td><%= link_to 'Destroy', question_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question attachment', new_question_attachment_path %>

app/views/question_attachments/new.html.erb
<h1>New question_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', question_attachments_path %>

app/views/question_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question_attachment.question_id %>
</p>

<p>
  <strong>File upload:</strong>
  <%= @question_attachment.file_upload_id %>
</p>

<p>
  <strong>Display order:</strong>
  <%= @question_attachment.display_order %>
</p>

<%= link_to 'Edit', edit_question_attachment_path(@question_attachment) %> |
<%= link_to 'Back', question_attachments_path %>