config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'welcome#index'

  devise_for :users
  resources :users

  resources :submission_questions

  resources :submissions

  resources :question_attachments

  resources :file_uploads

  resources :questions

end

app/models/file_upload.rb
class FileUpload < ActiveRecord::Base
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  before_action :set_file_upload, only: [:show, :edit, :update, :destroy]

  # GET /file_uploads
  # GET /file_uploads.json
  def index
    @file_uploads = FileUpload.all
  end

  # GET /file_uploads/1
  # GET /file_uploads/1.json
  def show
  end

  # GET /file_uploads/new
  def new
    @file_upload = FileUpload.new
  end

  # GET /file_uploads/1/edit
  def edit
  end

  # POST /file_uploads
  # POST /file_uploads.json
  def create
    @file_upload = FileUpload.new(file_upload_params)

    respond_to do |format|
      if @file_upload.save
        format.html { redirect_to @file_upload, notice: 'File upload was successfully created.' }
        format.json { render :show, status: :created, location: @file_upload }
      else
        format.html { render :new }
        format.json { render json: @file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_uploads/1
  # PATCH/PUT /file_uploads/1.json
  def update
    respond_to do |format|
      if @file_upload.update(file_upload_params)
        format.html { redirect_to @file_upload, notice: 'File upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @file_upload }
      else
        format.html { render :edit }
        format.json { render json: @file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_uploads/1
  # DELETE /file_uploads/1.json
  def destroy
    @file_upload.destroy
    respond_to do |format|
      format.html { redirect_to file_uploads_url, notice: 'File upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_upload
      @file_upload = FileUpload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_upload_params
      params.require(:file_upload).permit(:url, :name)
    end
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/views/file_uploads/_form.html.erb
<%= form_for(@file_upload) do |f| %>
  <% if @file_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_upload.errors.count, "error") %> prohibited this file_upload from being saved:</h2>

      <ul>
      <% @file_upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_uploads/edit.html.erb
<h1>Editing file_upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_upload %> |
<%= link_to 'Back', file_uploads_path %>

app/views/file_uploads/index.html.erb
<h1>Listing file_uploads</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_uploads.each do |file_upload| %>
      <tr>
        <td><%= file_upload.url %></td>
        <td><%= file_upload.name %></td>
        <td><%= link_to 'Show', file_upload %></td>
        <td><%= link_to 'Edit', edit_file_upload_path(file_upload) %></td>
        <td><%= link_to 'Destroy', file_upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File upload', new_file_upload_path %>

app/views/file_uploads/new.html.erb
<h1>New file_upload</h1>

<%= render 'form' %>

<%= link_to 'Back', file_uploads_path %>

app/views/file_uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @file_upload.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @file_upload.name %>
</p>

<%= link_to 'Edit', edit_file_upload_path(@file_upload) %> |
<%= link_to 'Back', file_uploads_path %>