config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'welcome#index'

  devise_for :users
  resources :users

  resources :submission_questions

  resources :submissions

  resources :question_attachments

  resources :file_uploads

  resources :questions

end

app/models/submission_question.rb
class SubmissionQuestion < ActiveRecord::Base
end

app/controllers/submission_questions_controller.rb
class SubmissionQuestionsController < ApplicationController
  before_action :set_submission_question, only: [:show, :edit, :update, :destroy]

  # GET /submission_questions
  # GET /submission_questions.json
  def index
    @submission_questions = SubmissionQuestion.all
  end

  # GET /submission_questions/1
  # GET /submission_questions/1.json
  def show
  end

  # GET /submission_questions/new
  def new
    @submission_question = SubmissionQuestion.new
  end

  # GET /submission_questions/1/edit
  def edit
  end

  # POST /submission_questions
  # POST /submission_questions.json
  def create
    @submission_question = SubmissionQuestion.new(submission_question_params)

    respond_to do |format|
      if @submission_question.save
        format.html { redirect_to @submission_question, notice: 'Submission question was successfully created.' }
        format.json { render :show, status: :created, location: @submission_question }
      else
        format.html { render :new }
        format.json { render json: @submission_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submission_questions/1
  # PATCH/PUT /submission_questions/1.json
  def update
    respond_to do |format|
      if @submission_question.update(submission_question_params)
        format.html { redirect_to @submission_question, notice: 'Submission question was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission_question }
      else
        format.html { render :edit }
        format.json { render json: @submission_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submission_questions/1
  # DELETE /submission_questions/1.json
  def destroy
    @submission_question.destroy
    respond_to do |format|
      format.html { redirect_to submission_questions_url, notice: 'Submission question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission_question
      @submission_question = SubmissionQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_question_params
      params.require(:submission_question).permit(:submission_id, :question_id, :position)
    end
end

app/helpers/submission_questions_helper.rb
module SubmissionQuestionsHelper
end

app/views/submission_questions/_form.html.erb
<%= form_for(@submission_question) do |f| %>
  <% if @submission_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission_question.errors.count, "error") %> prohibited this submission_question from being saved:</h2>

      <ul>
      <% @submission_question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :submission_id %><br>
    <%= f.number_field :submission_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submission_questions/edit.html.erb
<h1>Editing submission_question</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission_question %> |
<%= link_to 'Back', submission_questions_path %>

app/views/submission_questions/index.html.erb
<h1>Listing submission_questions</h1>

<table>
  <thead>
    <tr>
      <th>Submission</th>
      <th>Question</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submission_questions.each do |submission_question| %>
      <tr>
        <td><%= submission_question.submission_id %></td>
        <td><%= submission_question.question_id %></td>
        <td><%= submission_question.position %></td>
        <td><%= link_to 'Show', submission_question %></td>
        <td><%= link_to 'Edit', edit_submission_question_path(submission_question) %></td>
        <td><%= link_to 'Destroy', submission_question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission question', new_submission_question_path %>

app/views/submission_questions/new.html.erb
<h1>New submission_question</h1>

<%= render 'form' %>

<%= link_to 'Back', submission_questions_path %>

app/views/submission_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Submission:</strong>
  <%= @submission_question.submission_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @submission_question.question_id %>
</p>

<p>
  <strong>Position:</strong>
  <%= @submission_question.position %>
</p>

<%= link_to 'Edit', edit_submission_question_path(@submission_question) %> |
<%= link_to 'Back', submission_questions_path %>